### PR TITLE
Added A new project

### PR DESCRIPTION
**Pull request by Srijan-Baniyal**
DeepMiner 

It's a Project which works like a web scraper but digs deeper in terms of data mining.

### CODE REVIEW

**Comment by Srijan-Baniyal** [comment]
I had a question That :

Can I submit more PR after this is accepted ??

**Comment by Srijan-Baniyal** [comment]
@Aditya-devp  . Please check out my PR as soon as possible .

**Comment by Aditya-devp** [comment]
> I had a question That :
> 
> Can I submit more PR after this is accepted ??

ya sure

**Comment by Srijan-Baniyal** [comment]
Thank you so much for the response and opportunity.

**Pull request merged**
